/**
 * The portal's icon vocabulary. Import icons from here, not from lucide-react,
 * so one action always gets the same glyph across pages.
 */
export type { LucideIcon } from "lucide-react";
export {
  // Navigation / sections
  SquareKanban as BoardIcon,
  FolderKanban as ProjectsIcon,
  Bot as AgentsIcon,
  Cpu as RunnersIcon,
  Activity as ActivityIcon,
  Wrench as ToolsIcon,

  // Generic actions
  Plus as AddIcon,
  Pencil as EditIcon,
  Trash as DeleteIcon,
  Save as SaveIcon,
  X as CloseIcon,
  X as CancelIcon,
  Check as CheckIcon,
  Copy as CopyIcon,
  RefreshCw as RefreshIcon,
  Search as SearchIcon,
  ListFilter as FilterIcon,
  Eraser as ClearIcon,
  ArrowLeft as BackIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  ChevronsLeft as CollapseIcon,
  ChevronsRight as ExpandIcon,
  ExternalLink as ExternalLinkIcon,
  ArrowDownToLine as FollowIcon,
  Ellipsis as MoreIcon,
  Download as DownloadIcon,
  FolderOpen as BrowseIcon,
  LoaderCircle as SpinnerIcon,

  // Theme
  Sun as LightIcon,
  Moon as DarkIcon,
  Monitor as SystemIcon,

  // Task workflow
  CircleCheck as ApproveIcon,
  MessageSquareWarning as RequestChangesIcon,
  Sparkles as AiReviewIcon,
  CheckCheck as CompleteIcon,
  LockOpen as UnblockIcon,
  Ban as CancelTaskIcon,
  Send as SendIcon,
  GitBranch as BranchIcon,
  GitMerge as MergeIcon,
  FolderGit2 as WorktreeIcon,
  Flag as PriorityIcon,
  ClipboardList as PlanIcon,
  ShieldAlert as GuardrailIcon,
  ListChecks as CriteriaIcon,
  Compass as SteerIcon,
  FileText as DescriptionIcon,
  MessageSquare as ConversationIcon,
  RotateCcwClock as HistoryIcon,
  Clock as ClockIcon,
  Calendar as CalendarIcon,
  User as UserIcon,
  Hash as HashIcon,

  // Runners
  Play as StartIcon,
  Square as StopIcon,
  Terminal as TerminalIcon,
  ScrollText as LogsIcon,
  Timer as DurationIcon,
  Gauge as EffortIcon,
  Layers as ConcurrencyIcon,
  ShieldCheck as SafeModeIcon,
  ShieldOff as FullAccessIcon,
  BrainCircuit as ModelIcon,
  SlidersHorizontal as SettingsIcon,
  Folder as FolderIcon,

  // Status / feedback
  Info as InfoIcon,
  TriangleAlert as WarningIcon,
  CircleAlert as ErrorIcon,
  CircleCheck as SuccessIcon,
  CircleX as FailedIcon,
  Undo2 as RevertedIcon,
  Inbox as EmptyIcon,
  Zap as ZapIcon,
  Circle as CircleIcon,
  CircleDashed as PendingIcon,
  CircleDot as InProgressIcon,
  Eye as ReviewIcon,
} from "lucide-react";
